# @author: Hokyee Jau
# @date: 2023/10/26

import os.path as osp

# job shop scheduling
JOB_SHOP_CONFIG = dict(
    SCHEDULE_POOL_SIZE=2000,
    TIMELINE_POOL_SIZE=1000,
    TIMELINE_RANDOM_EMPTY_SIZE=2,
    TIMELINE_RANDOM_EMPTY_REPEAT_TIME=2,
    TIMELINE_LENGTH=10,
    TIMELINE_TIME_MAXIMA=10*10,
    JOB_SHOP_DATASET_COUNT=5,
    JOB_SHOP_SCHEDULING_ROOT = 'jsp/',
    JOB_SHOP_DATASET_DIR_FORMAT='L{TIMELINE_LENGTH}M{TIMELINE_TIME_MAXIMA}E{TIMELINE_RANDOM_EMPTY_SIZE}_{DIR_IDX}',
    JOB_SHOP_DATASET_PATH_FORMAT='{TIMELINE_IDX}.json'
)